######### Base Fish Config #########

# Setting up the Path
set -e fish_user_paths

source ~/.config/fish/aliases.fish
source ~/.config/fish/conf.d/_exports.fish

# Remove the default greeting
set fish_greeting

# User bin folder
set -g fish_user_paths ~/bin $fish_user_paths

######### Homebrew Config #########

# Homebrew generated by `brew shellenv`
set -gx HOMEBREW_PREFIX "/opt/homebrew";
set -gx HOMEBREW_CELLAR "/opt/homebrew/Cellar";
set -gx HOMEBREW_REPOSITORY "/opt/homebrew";
set -g fish_user_paths "/opt/homebrew/bin" $fish_user_paths
set -g fish_user_paths "/opt/homebrew/sbin" $fish_user_paths

# Stop brew install from updating everything
set -x HOMEBREW_NO_AUTO_UPDATE 1

######### Projects Config #########

# UQ Learn config
# set -x CAROOT /Users/tsyirvo/Projects/Clients/uq-learn/certs

######### Tools Config #########

# Flutter
# set -g fish_user_paths ~/tools/flutter/bin $fish_user_paths

# Maestro
# set -g fish_user_paths $HOME/.maestro/bin $fish_user_paths

# pnpm
set -gx PNPM_HOME "/Users/tsyirvo/Library/pnpm"
if not string match -q -- $PNPM_HOME $PATH
  set -gx PATH "$PNPM_HOME" $PATH
end

######### Android Config #########

# Android
set -x ANDROID_HOME ~/Library/Android/sdk
set -x ANDROID_SDK_ROOT ~/Library/Android/sdk
set -x ANDROID_AVD_HOME ~/.android/avd
set -gx PATH $ANDROID_HOME/platform-tools $PATH
set -gx PATH $ANDROID_HOME/emulator $PATH
# set -gx PATH $ANDROID_HOME/tools $PATH

######### Editor Config #########

# Set Cursor as default editor
set -x --global EDITOR cursor

######### Prompt Config #########

# Set bat theme
set -x BAT_THEME "Catppuccin Mocha"

# Set eza config dir
set -x EZA_CONFIG_DIR ~/.config/eza

# Start Starship Prompt
starship init fish | source

# zoxide config
zoxide init fish | source

# Set up fzf key bindings
fzf --fish | source

# Set up atuin
atuin init fish | source

fish_add_path ~/.local/bin

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init2.fish 2>/dev/null || :
