######### Base Fish Config #########

# Setting up the Path
set -e fish_user_paths

source ~/.config/fish/aliases.fish
source ~/.config/fish/conf.d/_exports.fish

# Remove the default greeting
set fish_greeting

# User bin folder
set -g fish_user_paths ~/bin $fish_user_paths

######### Homebrew Config #########

# TODO(env): check based on target machine (Intel vs ARM)
# Homebrew generated by `brew shellenv`
set -gx HOMEBREW_PREFIX "/opt/homebrew";
set -gx HOMEBREW_CELLAR "/opt/homebrew/Cellar";
set -gx HOMEBREW_REPOSITORY "/opt/homebrew/Homebrew";
set -q PATH; or set PATH ''; set -gx PATH "/opt/homebrew/bin" "/opt/homebrew/sbin" $PATH;
set -q MANPATH; or set MANPATH ''; set -gx MANPATH "/opt/homebrew/share/man" $MANPATH;
set -q INFOPATH; or set INFOPATH ''; set -gx INFOPATH "/opt/homebrew/share/info" $INFOPATH;
set -g fish_user_paths "/opt/homebrew/bin" $fish_user_paths

# Stop brew install from updating everything
set -x HOMEBREW_NO_AUTO_UPDATE 1

######### Projects Config #########

# UQ Learn config
set -x CAROOT /Users/tsyirvo/Projects/Clients/uq-learn/certs

######### Tools Config #########

# Flutter
set -g fish_user_paths ~/tools/flutter/bin $fish_user_paths

# Maestro
set -g fish_user_paths $HOME/.maestro/bin $fish_user_paths

######### Env management Config #########

# Node
set -x VOLTA_HOME $HOME/.volta
set -g fish_user_paths $VOLTA_HOME/bin $fish_user_paths
corepack enable --install-directory ~/.volta/bin

# Python
set -Ux PYENV_ROOT $HOME/.pyenv
fish_add_path $PYENV_ROOT/bin
pyenv init - | source

# Python bin folder
set -g fish_user_paths /Users/tsyirvo/Library/Python/3.10/bin $fish_user_paths

# rbenv config
status --is-interactive; and rbenv init - fish | source

######### Android Config #########

# Java
set -x JAVA_HOME (/usr/libexec/java_home -v 17)

# Android
set -x ANDROID_HOME ~/Library/Android/sdk
set -x ANDROID_SDK_ROOT ~/Library/Android/sdk
set -x ANDROID_AVD_HOME ~/.android/avd
set -gx PATH $ANDROID_HOME/platform-tools $PATH
set -gx PATH $ANDROID_HOME/tools $PATH
set -gx PATH $ANDROID_HOME/emulator $PATH

######### Editor Config #########

# Set Cursor as default editor
set -x --global EDITOR cursor

######### Prompt Config #########

# Set bat theme
set -x BAT_THEME "Catppuccin Mocha"

# Set eza config dir
set -x EZA_CONFIG_DIR ~/.config/eza

# Start Starship Prompt
starship init fish | source

# zoxide config
zoxide init fish | source

# Set up fzf key bindings
fzf --fish | source

# Set up atuin
atuin init fish | source
